### ISSUE TITLE
[Request] Support for .ogg files

### ISSUE THREAD

**Issue by Kuroonehalf** [LoredCast/soundboard#13]
I've made some electron apps before and know it should support playing .ogg files just fine, but at the moment it seems the program doesn't detect it as a valid file type. Could you extend it to support them too please?

**Comment by LoredCast** [comment]
Added in 0.2.3 [commit](https://github.com/LoredCast/soundboard/commit/5d8b11fee4d19836958adc77beb7f89301c8fcaf?diff=unified), [release](https://github.com/LoredCast/soundboard/releases/tag/v0.2.3). Hope you enjoy the soundboard and notify me of any further requests :)
Will look into an ffmpeg wrapper when I've got some time.
