### ISSUE TITLE
[bug] Volume setting isn't taken into account until it's changed

### ISSUE THREAD

**Issue by Kuroonehalf** [LoredCast/soundboard#15]
To reproduce:
- Boot up program
- Play any sounds
- Sounds will play at 100% volume, ignoring the volume setting.  It will only start respecting it after you've changed the volume.
Some value is probably not being initialized correctly.

**Comment by LoredCast** [comment]
Typo, took some investigation lol. Fixed in [0.2.4](https://github.com/LoredCast/soundboard/releases/tag/v0.2.4)
