### ISSUE TITLE
Add minimize/close window system tray and restore window from tray

### ISSUE THREAD

**Issue by TapsHTS** [LoredCast/soundboard#3]
Can you add this function ?

**Comment by TapsHTS** [comment]
Like Discord:
![image](https://user-images.githubusercontent.com/61658427/113681291-167c5180-96c2-11eb-8374-7bbcdda2bb12.png)

**Comment by LoredCast** [comment]
I've read your suggestion, and I'm sorry, they are not treated as carefully as I wished. There are a lot of exams recently and I had to step down the work on this repo but coming releases, probably 2 or so down the road will have a 'minimize to taskbar' option. Immediate attention right now is eome bug fixing and accessibility.

Thank you for your ideas!

**Comment by TapsHTS** [comment]
Nice 👌

**Comment by LoredCast** [comment]
Tray icon and functionality is added in 0.2.2
