### ISSUE TITLE
stop audio button

### ISSUE THREAD

**Issue by internet-person** [LoredCast/soundboard#5]
i just downloaded and i see one thing lacking, the ability to stop playing an audio clip without closing the program. 

its not really not really necessary as most clips are under 15 seconds, but short of pause/play/stop buttons or a timeline control for audio playback (like a music player) this feature would have the biggest impact on the ability to play audio files well over 20 seconds like whole songs.

(thanks for making a soundboard that doesnt look like it comes from the early 2000s :)

**Comment by LoredCast** [comment]
Thanks for your first issue! Stopping functionality is made possible by clicking on the sound twice, i.e. once if it is already playing. Check your version number if this is not the case in your installation.

**Comment by internet-person** [comment]
huh so it is, i stand corrected. thank you. 

while i have your ear for the moment, is there any way to either make the buttons bigger or the text smaller? im running into issues with my labels being cut off mid word and i noticed that in the screenshot the buttons are about twice the normal size.

**Comment by LoredCast** [comment]
This is indeed an issue occuring with longer textfields, I'm aware of that. Please open a new issue for that specifically so I don't lose track of it. :)
